services:
  web:
    image: php:7.4-apache
    container_name: demo_web
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      - SMTP=mailhog
      - smtp_port=1025
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: demo_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
