version: "3"
services:
    image: php:7.4-apache
    container_name: demo_web
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      # Estas variables no se usan directamente, pero te sirven de referencia para usar en php.ini
      - SMTP=mailhog
      - smtp_port=1025
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: demo_mailhog
    ports:
      - "1025:1025"  # Puerto SMTP
      - "8025:8025"  # Interfaz web
